PROGRAM PRIVATE_VARIABLE_OPENMP

	USE OMP_LIB
	IMPLICIT NONE
	INTEGER :: THREAD_NUMBER
	
	CALL OMP_SET_NUM_THREADS(10)
	
	!$OMP PARALLEL PRIVATE(THREAD_NUMBER)
	
	THREAD_NUMBER = OMP_GET_THREAD_NUM()
	
	!$OMP CRITICAL
		PRINT *, 'THIS IS THREAD: ', THREAD_NUMBER
	!$OMP END CRITICAL
	
	!$OMP END PARALLEL

END PROGRAM PRIVATE_VARIABLE_OPENMP
